//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoKeeper.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo_Pet
    {
        public int Id { get; set; }
        public Nullable<int> PhotoId { get; set; }
        public Nullable<int> PetId { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
